import './globals.css';
import type { Metadata } from 'next';
import { Bebas_Neue, Inter } from 'next/font/google';
import Header from '@/components/Header/Header';
import { ReactNode } from 'react';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/app/api/auth/[...nextauth]/route';
import AuthProvider from '@/providers/AuthProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Online Store',
    description: 'Generated by create next app',
};

const bebasNeue = Bebas_Neue({
    weight: '400',
    subsets: ['latin'],
    variable: '--font-bebasNeue',
    preload: true,
});

export default async function RootLayout({
    children,
}: {
    children: ReactNode;
}) {
    const session = await getServerSession(authOptions);
    return (
        <html lang="en" className={`${bebasNeue.variable}`}>
            <body className={inter.className}>
                <AuthProvider session={session}>
                    <Header />
                    <main className="container mb-20">{children}</main>
                </AuthProvider>
            </body>
        </html>
    );
}
