import './globals.css';
import type { Metadata } from 'next';
import { Bebas_Neue, Inter } from 'next/font/google';
import Providers from '@/components/Providers';
import Header from '@/components/header/Header';
import React from 'react';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

const bebasNeue = Bebas_Neue({
    weight: '400',
    subsets: ['latin'],
    variable: '--font-bebasNeue',
});

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" className={`${bebasNeue.variable}`}>
            <body className={inter.className}>
                <Providers>
                    <Header />
                    <main className="container">{children}</main>
                </Providers>
            </body>
        </html>
    );
}
